public enum MessageFlag {
    SIGN_IN,
    SUCCESSFUL_SIGN_IN,
    FAILED_SIGN_IN,

    SIGN_UP,
    SUCCESSFUL_SIGN_UP,
    FAILED_SIGN_UP,

    DEFAULT_MESSAGE,
    LOG_OUT_FROM_SERVER,
    LOG_OUT_FROM_CHAT,

    DATABASE_OFFLINE
}
